# Artificial Neural Network

### Importing the libraries !

In [ ]:
import tensorflow as tf
print(tf.config.list_physical_devices())
print(tf.version.VERSION) 

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'), PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
2.13.0


In [2]:
import numpy as np
import pandas as pd
import tensorflow as tf 

In [3]:
print(tf.__version__)

2.13.0


## Part 1 - Data Preprocessing

## Part 1 - Data Preprocessing

### Importing the dataset

- foor X we don't need to take rownumber, costurmer id and surname, so we only takes the column starting from creditscore to except eestimated salary
- for X so we use 3:-1 to do this formation it takes starting 3.columun (0 index for python) then not included last columun which we udes -1

In [4]:
dataset = pd.read_csv('/Users/nisankarsan/Downloads/Codes/Deep Learning A-Z/Part 1 - Artificial Neural Networks (ANN)/Churn_Modelling.csv')
x = dataset.iloc[:,3:-1].values #all rows, all columns except the last one which is the target variable (Exited)
y = dataset.iloc[:,-1].values #dependent variable vector (all rows, only the last column) whicc is the target variable (Exited)

In [5]:
print(x)


[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


the 1 below is the first costumer row which is stay in the bank

In [6]:
print(y)

[1 0 1 ... 1 1 0]


### Encoding categorical data

there are 2 categorical variables in the dataset 
1. the country of residence of the costumers(which is 2.column of X)
2. gender of the costumer( which is 3.column of X)

we'll have to so some encoding work here to encode these categorical data in either simple labels, 0 or 1 for the gender or some hot encoding for this categorical which indeed there is o relationship order between these values, between the categories France, Spain ang Germany 

Label Encoding the "Gender" column

In [7]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder() 
#object of the class LabelEncoder which is used to encode the categorical variable into numerical variable
x[:,2] = le.fit_transform(x[:,2])  #3.column but python is 0 based so it is the 2nd column
#encoding the gender column into numerical values (0,1) using the fit_transform method of the LabelEncoder class object le 
#takes all the rows of the 3rd column of the x matrix and encodes them into numerical values and replaces them in the x matrix itself

there is relationship with female and male

In [8]:
print(x) #0 for Female, 1 for Male

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding the "Geography" column

but there is no relationsship between the countries, so we do hot-encoding

In [9]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
# the countries in the 1st column are encoded into 3 columns using the OneHotEncoder class
X = np.array(ct.fit_transform(x))

In [23]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


the first column is France, \
the second column is Germany and \
the third column is Spain \
(0,0,1) for Spain, \
(0,1,0) for Germany \
(1,0,0) for France 

### Splitting the dataset into the Training set and Test set

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=0)
#splitting the dataset into training and testing set using the train_test_split method of the model_selection class of the sklearn library
#X_train is the training set of the independent variables
#X_test is the testing set of the independent variables
#y_train is the training set of the dependent variable
#y_test is the testing set of the dependent variable
#test_size=0.2 means 20% of the dataset is used for testing and 80% is used for training
#random_state=0 is used to get the same output as the instructor


### Feature Scaling

when you build ANN you have to apply feature scaling, we apply feature scaling to all out features


Feature Scaling is critical to ensure accurate outcomes, faster computations, and to prevent any single feature from dominating the model due to its range.

In [12]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
#scaling the independent variables using the StandardScaler class of the preprocessing module of the sklearn library
#fit_transform method is used to fit the StandardScaler object to the training set and transform it
#transform method is used to transform the testing set using the same object that was fitted to the training set



## Part 2 - Building the ANN

### Initializing the ANN

- the certain class is sequential class which allows exactly to buil an artificial neural network but as a sequence of  layers as opposed to computational graph
- start initial layer then have the fully connected layers up to the final output layer

In [13]:
import tensorflow as tf


In [14]:
ann = tf.keras.models.Sequential() #object of the Sequential class of the keras module of the tensorflow library
#used to initialize the neural network


2024-11-08 19:42:15.385962: I metal_plugin/src/device/metal_device.cc:1154] Metal device set to: Apple M2
2024-11-08 19:42:15.385994: I metal_plugin/src/device/metal_device.cc:296] systemMemory: 16.00 GB
2024-11-08 19:42:15.386017: I metal_plugin/src/device/metal_device.cc:313] maxCacheSize: 5.33 GB
2024-11-08 19:42:15.386097: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:303] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2024-11-08 19:42:15.386143: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:269] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


### Adding the input layer and the first hidden layer

In [15]:
# Adding the input layer and the first hidden layer of the neural network
# Dense class of the layers module of the keras library is used to add the input layer and the first hidden layer
# units=6 is the number of neurons in the first hidden layer which
# activation='relu' is the activation function used in the first hidden layer which
# is the rectifier function (relu) because it is the first hidden layer and the input layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))


### Adding the second hidden layer

In [16]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))


### Adding the output layer

In [17]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))
# Adding the output layer of the neural network
# units=1 is the number of neurons in the output layer 
# which is 1 because it is a binary classification problem (0 or 1) 
# activation='sigmoid' is the activation function used in the output layer
# which is the sigmoid function because it is a binary classification problem (0 or 1)


## Part 3 - Training the ANN

### Compiling the ANN

- compile ANN with an optimizer, a loss function, and a metric which accuracy because we're doing some classification. 
-  the default is Adam Optimizer, which is a very performance optimizer that can perform the Stochastic Gradient Descent. 

Stochastic Gradient Descent allow to do:
- update the weights, 
reduce the cost function error between your predictions and real result. Each iteration compare the predictions in a batch to the real results in the same batch. And that the optimizer here will update the weight through Stochastic Gradien descent to at the next iteration, hopefully reduce the loss.

What is batch size? The batch size is a hyperparameter that defines the number of samples to work through before updating the internal model parameters.

loss function which is the way to compute the difference between the predictions and the real results, and the accuracy of course beacuse that's our final evaluation metrics 

For loss function:
- if you're doing binary classification, you know classification when you have to predict a binary outcome so the lost function always be the following one entered in quotes which is "binary_crossentropy" and activation sigmoid.
- if you're doing non-binary classification, predicting 3 different categries, you use "category called cross entropy loss". activation shouldn't be sigmoid but sofmax

In [18]:
ann.compile(optimizer = 'adam', loss ='binary_crossentropy', metrics =['accuracy'] )

### Training the ANN on the Training set

How starting training ?
- take out ANN and then call a new method which will perform the training and enter couple of parameters
- the fit method takes always the same parameters, first X_train which is matrix of features of the training set.
- Y_train for the dependent variable vector of the training set.
- batch size, batch learning is always more efficient and more performant when training an artificial neural network, meaning that instead of comparing your prediction to the real result, one by one to compute and reduce the loss, gonna do that with several predictions compared to several results into a batch. And the batch size parameter gives exactly the number of predictions you want to have in the batch to be compared to that same number of result. And the classic value of the batch size that usually chosen 32, if you don't want to spend too much time tuning this hyper parameter, choose default value 32

- the number of epochs: the neural network has to be trained over certain amount of epochs so as to improve the accuracy over time.  Don't choose samll epochs because neural network needs a certain amount of epochs in order to learn properly, learn the correlations to get ultimate best predictions

In [19]:
ann.fit(X_train, y_train, batch_size=32, epochs=100) 

Epoch 1/100


2024-11-08 19:42:35.040294: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


250/250 [==============================] - 3s 3ms/step - loss: 0.7047 - accuracy: 0.6386
Epoch 2/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4707 - accuracy: 0.7889
Epoch 3/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4406 - accuracy: 0.8059
Epoch 4/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4344 - accuracy: 0.8066
Epoch 5/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4320 - accuracy: 0.8085
Epoch 6/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4320 - accuracy: 0.8070
Epoch 7/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4318 - accuracy: 0.8081
Epoch 8/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4321 - accuracy: 0.8081
Epoch 9/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4325 - accuracy: 0.8087
Epoch 10/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4334 - accuracy: 0.8064
E

## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation

sc is the object of the StandardScaler class which is used to scale the independent variables

- do not forget to put [[]] that any input of the predict method must be a 2D array. Whether it is the test set to predict an ensemble of outcomes for an ensemble of observations or whether it is a single prediction, well anything has to be in a double pair of square brackets [[]] which therefore makes a 2D array

In [ ]:
#Predicting result for Single Observation
print(ann.predict(sc.transform([[1, 0, 0, 1,600, 40, 3, 60000, 2, 1, 1,50000]])) > 0.5)



1/1 [==============================] - 0s 14ms/step
[[False]]


**Homework**

Use our ANN model to predict if the customer with the following informations will leave the bank:

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer?

**Solution**

Therefore, our ANN model predicts that this customer stays in the bank!

**Important note 1:** Notice that the values of the features were all input in a double pair of square brackets. That's because the "predict" method always expects a 2D array as the format of its inputs. And putting our values into a double pair of square brackets makes the input exactly a 2D array.

**Important note 2:** Notice also that the "France" country was not input as a string in the last column but as "1, 0, 0" in the first three columns. That's because of course the predict method expects the one-hot-encoded values of the state, and as we see in the first row of the matrix of features X, "France" was encoded as "1, 0, 0". And be careful to include these values in the first three columns, because the dummy variables are always created in the first columns.

### Predicting the Test set results

### Making the Confusion Matrix